### ISSUE TITLE
MethodError: no method matching metadata_model

### ISSUE THREAD

**Issue by songroom2016** [alan-turing-institute/MLJDecisionTreeInterface.jl#20]
julia> using MLJDecisionTreeInterface
[ Info: Precompiling MLJDecisionTreeInterface [c6f25543-311c-4c74-83dc-3ea6d1015661]
ERROR: LoadError: MethodError: no method matching metadata_model(::Type{MLJDecisionTreeInterface.DecisionTreeClassifier}; input_scitype=ScientificTypesBase.Table{<:Union{AbstractVector{<:ScientificTypesBase.Count}, AbstractVector{<:ScientificTypesBase.OrderedFactor}, AbstractVector{<:ScientificTypesBase.Continuous}}}, target_scitype=AbstractVector{<:ScientificTypesBase.Finite}, human_name="CART decision tree classifier", load_path="MLJDecisionTreeInterface.DecisionTreeClassifier")
Closest candidates are:
  metadata_model(::Any; input, target, output, weights, descr, path, input_scitype, target_scitype, output_scitype, supports_weights, docstring, load_path) at C:\Users\songroom\.julia\packages\MLJModelInterface\txhfr\src\metadata_utils.jl:101 got unsupported keyword argument "human_name"
Stacktrace:
 [1] kwerr(::NamedTuple{(:input_scitype, :target_scitype, :human_name, :load_path), Tuple{UnionAll, UnionAll, String, String}}, ::Function, ::Type)
   @ Base .\error.jl:163
 [2] top-level scope
   @ C:\Users\songroom\.julia\packages\MLJDecisionTreeInterface\WijC5\src\MLJDecisionTreeInterface.jl:286
 [3] include
   @ .\Base.jl:418 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base .\loading.jl:1318
 [5] top-level scope
   @ none:1
 [6] eval
   @ .\boot.jl:373 [inlined]
 [7] eval(x::Expr)
   @ Base.MainInclude .\client.jl:453
 [8] top-level scope
   @ none:1
in expression starting at C:\Users\songroom\.julia\packages\MLJDecisionTreeInterface\WijC5\src\MLJDecisionTreeInterface.jl:1
ERROR: Failed to precompile MLJDecisionTreeInterface [c6f25543-311c-4c74-83dc-3ea6d1015661] to C:\Users\songroom\.julia\compiled\v1.7\MLJDecisionTreeInterface\jl_DEAB.tmp.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base .\loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base .\loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base .\loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base .\loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:997

julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://pkg.julialang.org

**Comment by ablaom** [comment]
@songroom2016 Thanks for reporting!

Looks like your using MLJDecisionTreeInterface with an older version of MLJModelInterface (which should not be possible but is). The workaround is to update your project, say by updating MLJ (ie, try `using Pkg; Pkg.update("MLJ")`). You want to be using MLJModelInterface 1.4 or greater. Check your Manifest.toml to see what version you are using (in the REPL you can do `]status -m`).

**Proper fix.** I see that we should have bumped the compat for MLJModelInterface in MLJDecisionTreeInterface 0.2.0.

So we should:

- [x]  release a patch with the compat update
- [x] pull MLJDecisionTreeInterface 0.2.0 and 0.2.1; pending: https://github.com/JuliaRegistries/General/pull/57936
