### ISSUE TITLE
Incorporate feature importance

### ISSUE THREAD

**Issue by kescobo** [alan-turing-institute/MLJDecisionTreeInterface.jl#24]
From https://github.com/JuliaAI/DecisionTree.jl/pull/182

@OkonSamuel [you said](https://github.com/JuliaAI/DecisionTree.jl/pull/166#issuecomment-1168756656) you were working on it? Mostly opening this issue so I can track it, I'm eager to put it to use!

**Comment by kescobo** [comment]
From slack, related PRs:

https://github.com/JuliaAI/MLJModelInterface.jl/pull/148
https://github.com/JuliaAI/MLJBase.jl/pull/798

**Comment by ablaom** [comment]
DecisionTree provides three different feature importances, so I expect we need to add a hyper-pararameter to control the active one.

**Comment by ablaom** [comment]
The apparatus is now in place for this to proceed. The key documentation is here:

https://github.com/JuliaAI/MLJModelInterface.jl/blob/1628202d5537e8b423fd1d542f7dfbb8e92fb051/src/model_api.jl#L169

**Comment by OkonSamuel** [comment]
closed by #28
