### ISSUE TITLE
DecisionTreeRegressor and DecisionTreeClassifier do not allow `n_subfeatures=-1`. 

### ISSUE THREAD

**Issue by john-waczak** [alan-turing-institute/MLJDecisionTreeInterface.jl#33]
The docs for `DecisionTreeClassifier` hyperparameter `:n_subfeatures` state: 
```
n_subfeatures=0: number of features to select at random (0 for all, -1 for square root of number of features)
```
However the value `-1` leads to the error  "number of features -1 must be >= zero ". I'm not sure if the issue should be handled at this interface or in DecisionTree.jl itself as the function `build_forest()` has 
```julia
if n_subfeatures == -1
    n_features = size(features, 2)
    n_subfeatures = round(Int, sqrt(n_features))
 end
```

while the function `build_tree()` does not. See [this link](https://github.com/JuliaAI/DecisionTree.jl/blob/1b1a35b3ce76f455844b3400d5d4dcd0cc8c0a5e/src/regression/main.jl) for the classifier and [this other link](https://github.com/JuliaAI/DecisionTree.jl/blob/1b1a35b3ce76f455844b3400d5d4dcd0cc8c0a5e/src/regression/main.jl) for the regressor.

**Comment by ablaom** [comment]
I believe the square-root option is probably only useful in the case of forests. Generally I haven't found feature subsampling at nodes useful for single trees. In any case, as you observed, it is not provided as an option in DecisionTree.jl trees. Unless you have a use-case for this kind of regularisation  in single trees, I suggest we regard this as an error in the docs.

**Comment by john-waczak** [comment]
That sounds good to me. I'll update the docs.
