### ISSUE TITLE
Version 0.3.1 broke tests in MCMCChains

### ISSUE THREAD

**Issue by devmotion** [alan-turing-institute/MLJDecisionTreeInterface.jl#47]
It seems the recent changes to the implementation of `fit` in 0.3.1, in particular the additional arguments that are now required, broke downstream tests in MCMCChains: https://github.com/TuringLang/MCMCChains.jl/issues/400 and https://github.com/TuringLang/MCMCChains.jl/pull/402

My main question before making any additional changes downstream is: Is that a bug in MLJDecisionTreeInterface or a problem with the implementation in MCMCChains (or rather MCMCDiagnosticTools)?

**Comment by ablaom** [comment]
Will reply at https://github.com/TuringLang/MCMCChains.jl/issues/400.

Closing in favour of #48
